### ISSUE TITLE
Install without nodejs

### ISSUE THREAD

**Issue by oquidave** [dominictarr/wifi.sh#12]
Hey, I like this tool. How can I install it without first having nodejs?

**Comment by dominictarr** [comment]
you just need to get https://raw.githubusercontent.com/dominictarr/wifi.sh/master/index.sh
into you path...
`curl https://raw.githubusercontent.com/dominictarr/wifi.sh/master/index.sh > /usr/bin/wifi.sh; chmod +x /usr/bin/wifi.sh`

something like that would work.

you can also install it using `bpkg` http://www.bpkg.io/pkg/wifi (along with nearly 20 other modules ;)

**Comment by oquidave** [comment]
Hey great thanks. Installed it on my desktop, will try it on the Pi.

**Comment by dominictarr** [comment]
thanks. let me know how it goes. This is what I use on arch, and it works pretty great. But havn't tested it on other systems. occasionally I get an issue from someone, but I don't know whether they are using it as their main thing.

**Comment by stevemao** [comment]
it maybe worth it to add it to homebrew

**Comment by dominictarr** [comment]
@stevemao this depends on `wpa_supplicant`. I assumed that OSX doesn't have that... If it does, then it should work.

**Comment by dominictarr** [comment]
I have documented install instructions with and without npm,
closing this issue
